# DOCKER-VERSION 0.4.8

from  strider/strider:preclone
maintainer  Jared Forsyth <jared@jaredforsyth.com>

# grab strider
run  git clone https://github.com/Strider-CD/strider.git /src

# update to Strider Version 1.3.1
run  cd /src && git pull && git reset --hard 1.3.1

# Install app dependencies
run  cd /src; npm install

